### ISSUE TITLE
Mark as read not working - 1.0.0-beta.5

### ISSUE THREAD

**Issue by zolero** [Secreto31126/whatsapp-api-js#119]
It should be, i'm sorry but is the library even being tested before submitting, these things should work...
```ts
body: JSON.stringify({ 
     messaging_product: "whatsapp", 
     status: "read", 
     message_id: message_id
 }) 
```

https://github.com/Secreto31126/whatsapp-api-js/blob/58e84d70f6bc88c6a73c4b87dd464951a5a7be0d/src/index.ts#L310-L314

**Comment by Secreto31126** [comment]
That's the magic of betas, it might sometimes break 🙃.

That behind, I'm actually curious to know how the bug got into, as you can see it is correctly written in stable (0.8.2). Most probably it was a variable renaming mistake, ups.

I used to have a setup to manually test most of the library features in Google App Script, but with the rewrite into TS I had been struggling with the transition. GAS is supposed to support TS, but it has so many limitations that I gave up, so I need to create a full system from the ground to test every method on a probably paid service. Btw, it's the main reason I'm still holding v1 on beta, other people are beta testing the code for me and finding bugs like yours :)

Anyway, I will fix the bug right now, but don't expect a new release until Sunday or Monday when I'm back home.

Sorry, and thanks for mentioning the issue!
