### ISSUE TITLE
send multiple messages in batch

### ISSUE THREAD

**Issue by wander4747** [Secreto31126/whatsapp-api-js#141]
**Is your feature request related to a problem? Please describe.**
send multiple messages in batch

**Describe the solution you'd like**
there could be a way to send several messages... like inside a loop

**Describe alternatives you've considered**

**Additional context**

**Comment by Secreto31126** [comment]
I love the idea! A signature like this should do the job:

```ts
async broadcastMessage(phoneID: string, to: string[], message: ClientMessage, context?: string): Promise<Array<Awaited<ReturnType<typeof this.sendMessage>>>>;
// This is one ugly return type 😂
```

It's worth noting that the API has a rate limit, which could make this function fail if the array is too long. I don't remember the exact number from the top of my head, but I think it was along the hundreds per minute. Will need to mention it in the documentation

Thanks for creating the request!

**Comment by wander4747** [comment]
Has a limit of 80 messages per second.

I also think it's worth putting a timer of seconds when looping 80 messages. hahahaha

**Comment by Secreto31126** [comment]
[On the documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/overview?locale=en_US#key-differences) I'm seeing a message throughput of 500 per second, way better than 80. I will add a rate limiter of 200 messages per second, customizable via parameters.

**Comment by Secreto31126** [comment]
[Proof reading the documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/overview?locale=en_US#throughput), you are right about the 80 mps, but it seems to be possible to get 500 mps by request.

I will make the default rate limit 50 mps, and keep the option to customize the batch sizes.
