### ISSUE TITLE
Is this project accepting Contributions?

### ISSUE THREAD

**Issue by TheYuriG** [Secreto31126/whatsapp-api-js#152]
Didn't see anything about contributing on the Documentation, but sorry if I missed it.

**Comment by Secreto31126** [comment]
Sure! Feel free to write any PR you want.

I will copy from the SvelteKit repo and ask you to discuss what you will be adding/changing in an issue before the PR (it can be here).

I will read about adding a CONTRIBUTE.md file later today.

Thanks :)

**Comment by TheYuriG** [comment]
I haven't dig deep in the code itself yet, so i don't think i can contribute with that just yet. First i would want to fix the Readme and correct some typos, then i would slowly start building the Deno documentation since that's the variation of the library that I'll be using.
