### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by Secreto31126** [Secreto31126/whatsapp-api-js#169]
Param interactive['type'] must be one of {ADDRESS_MESSAGE, BUTTON, CATALOG_MESSAGE, GALAXY_MESSAGE, LIST, MENU_OPTIONS, MESSAGE_WITH_LINK, MESSAGE_WITH_LINK_STATUS, ORDER_DETAILS, ORDER_STATUS, PRODUCT, PRODUCT_LIST}

**Comment by Secreto31126** [comment]
I was unable to discover more about the GALAXY_MESSAGE, I found out it requires an action which needs a CTA, but the error wasn't telling which value it should have.

I will consider searching more about MENU_OPTIONS, MESSAGE_WITH_LINK and MESSAGE_WITH_LINK_STATUS in the future.

**Comment by RahulLanjewar93** [comment]
@Secreto31126 i think cta also needs to be added?

**Comment by Secreto31126** [comment]
Yeah, it has been on my to-do list since it was released, but right now I don't have enough time to do it. Tomorrow is my last exam of the month (hopefully) and I will be able to update the library.

**Comment by RahulLanjewar93** [comment]
> Yeah, it has been on my to-do list since it was released, but right now I don't have enough time to do it. Tomorrow is my last exam of the month (hopefully) and I will be able to update the library.

Ok, I am going through the entire source code as well. 
I will help wherever possible. Thanks :)

**Comment by Secreto31126** [comment]
Param interactive['type'] must be one of {~ADDRESS_MESSAGE~, ~BUTTON~, ~CATALOG_MESSAGE~, ~CTA_URL~, ~FLOW~, FORM_MESSAGE, ~LIST~, ~LOCATION_REQUEST_MESSAGE~, ~MENU_OPTIONS~, MESSAGE_WITH_LINK, MESSAGE_WITH_LINK_STATUS, ~ORDER_DETAILS~, ~ORDER_STATUS~, ~PRODUCT~, ~PRODUCT_LIST~, VOICE_CALL}

Voice calls!?
