### ISSUE TITLE
EoL for Node14 and 17

### ISSUE THREAD

**Issue by Secreto31126** [Secreto31126/whatsapp-api-js#177]
The library should be updated to reflect the deprecated Node versions, specially in the setup/node.ts file.

Also, I think it would be nice to plan the v2 release to match with [node16 EoL](https://github.com/nodejs/Release) on September, 11.

Things to do for a still tbd v2:

- [x] Set package.json engine to `">=18"`
 - [x] Update #168 monkey patch
 - [x] ~Update src/setup/node.ts to only support @^18~ Deprecate node 16 method on src/setup/node.ts
 - [x] Update github actions
 - [ ] ~_Maaaaabye_ consider removing CommonJS support (although I'm happy with the results I got with esbuild)~

**Comment by hys-oc** [comment]
Great library, some things on the examples are a bit confusing, would recommend to add how you import everything on the examples since you kinda have to deduct from where to import it
