### ISSUE TITLE
Error while compiling typescript project

### ISSUE THREAD

**Issue by HysMX** [Secreto31126/whatsapp-api-js#179]
**Describe the bug**
I'm getting the error

node_modules/whatsapp-api-js/lib/types/index.d.ts(147,147): error TS2304: Cannot find name 'this'.

**To Reproduce**
1. While compiling a typescript project which has in any file the broadcastMessage function it fails to compile

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Runtime Node @18
 - Library Version [e.g. 1.0.2]

**Comment by HysMX** [comment]
![image](https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/9a95cfbe-eea6-465a-97e1-52528f82c683)

Mi discord es hysmx si gustas conversar mas sobre el tema

**Comment by DiegoCarrillogt** [comment]
@Secreto31126, 
Hi! I've been getting the same error as @HysMX  :)

**Comment by Secreto31126** [comment]
Hey, I'm unable to replicate the issue with the following code:

```typescript
import WhatsAppAPI from "whatsapp-api-js";
import { Text } from "whatsapp-api-js/messages";

const Whatsapp = new WhatsAppAPI({
        token: "fake",
        secure: false
});

const m = new Text("Hi");
Whatsapp.broadcastMessage("fake", ["1", "2"], m);
```

Could you send me a snippet of the broken code?

**Comment by HysMX** [comment]
Hi, the code fails to compile if you include the constructor in any place even if it’s not being ran at the moment, i’m using the node 18 whatsapp constructor as is a nodejs project and not a web one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Secreto31126** [comment]
Out of curiosity, what's your typescript version?

I'm reading an issue in their repo, and it seems like the syntax `typeof this.blablabla` was bugged until v4.4.

https://github.com/microsoft/TypeScript/pull/43898

They also mention workarounds for it, such as `this["method"]` or `ClassName.method`, and if needed I think the latter could be a clean solution.

**Comment by Secreto31126** [comment]
A little more looking around, I found out there's an option to skip library type checks in tsconfig.json:

```json
"skipLibCheck": true
```

This will definitely fix/silent the issue, although I'm not sure how it will handle the return type.

Let me know if it works for both of you.

**Comment by DiegoCarrillogt** [comment]
Hey! thank you for giving a look! will def take a look at this :)

**Comment by Secreto31126** [comment]
Closed due to inactivity
