### ISSUE TITLE
chore: update readme to use `e.query` instead of `JSON.parse(e.params)`

### ISSUE THREAD

**Issue by RahulLanjewar93** [Secreto31126/whatsapp-api-js#191]
**Describe the bug**
Currently in readme we are passing `e.params`, however the data is in `e.query`

https://github.com/Secreto31126/whatsapp-api-js/blob/03ffad10729e88289808593e31e995d2a827ed34/README.md?plain=1#L110-L112
This throws error. since e.params is {};

**Expected behavior**
Use `e.query` instead of `JSON.parse(e.params)`

**Desktop (please complete the following information):**
 - mac
 - node@16
 - 1.0.3

**Comment by Secreto31126** [comment]
This is correct. I'm surprised I didn't catch it earlier.

If you want, feel free to open a PR, or I can fix it in a few hours.

Thanks!
