### ISSUE TITLE
All Types not exported when importing the package 

### ISSUE THREAD

**Issue by RahulLanjewar93** [Secreto31126/whatsapp-api-js#202]
https://github.com/Secreto31126/whatsapp-api-js/blob/c38513f7027fbf5176e45896ea3f2a2e2996ee2e/package.json#L19

This file does not include all the types, I think we should export all the types from the `index.d.ts` file?

**Comment by Secreto31126** [comment]
Sorry, I didn't follow, what do you mean with not all types are included? The file types.ts includes most of them, so index.ts doesn't become thousands lines long.

If you mean that dependency types are missing, I think the issue might be on tsconfig, which although it's configured to include node and undici types, I don't think it's working as expected.

**Comment by RahulLanjewar93** [comment]
`ClientMessage` is not exported from `index.ts`, although we do import it I think we don't export it. 
I had to import it separately from `whatsapp-api-js/types`
https://github.com/Secreto31126/whatsapp-api-js/blob/c38513f7027fbf5176e45896ea3f2a2e2996ee2e/package.json#L43-L44

**Comment by Secreto31126** [comment]
I don't think the main file should contain those types, especially since most of them are for "internal" use (isomorphism or inheritance)

If the dev wants/needs to access them it's allowed to do so, but it shouldn't be an encouraged usage.

**Comment by Secreto31126** [comment]
Closed as stale
