### ISSUE TITLE
Cryptic error if a ponyfill is required

### ISSUE THREAD

**Issue by edengby** [Secreto31126/whatsapp-api-js#239]
**Describe the bug**
When I run the exmple from here: 
https://github.com/Secreto31126/whatsapp-api-js#:~:text=Now%20you%20can%20write%20code%20like%20this%3A
I fill in the TOKEN and APP_SECRET and I get the error:
Error: subtle is not defined in the enviroment, please provide a valid ponyfill object with the parameter 'ponyfill.subt
le'.

**To Reproduce**
1. Open new project
2. Import the project
3. Copy the exmple
4. Fill in the TOKEN and SECRET
5. Run it
6. Get the error

**Expected behavior**
The app should run locally.

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Runtime Node.js v18.16.0
-   Library Version 2.1.1

**Comment by Secreto31126** [comment]
You might want to use the setup helpers defined in "whatsapp-api-js/setup"

https://whatsappapijs.web.app/functions/setup.Node18.html
https://github.com/Secreto31126/whatsapp-api-js/blob/main/EXAMPLES/main.md#using-the-setup-helpers
https://github.com/Secreto31126/whatsapp-api-js/blob/main/ENVIRONMENTS.md

I will update the error message to make it clear there's a method to fix this issue.
