### ISSUE TITLE
Text is not a constructor

### ISSUE THREAD

**Issue by HysMX** [Secreto31126/whatsapp-api-js#244]
**Describe the bug**
Can't create a text object to send a message, it returns Text is not a constructor

**To Reproduce**
```js
import { Text, Image, Document } from "whatsapp-api-js/messages";

const msg = new Text(`Copia este mensaje y envíalo al proveedor para que pueda identificarte:
Este es el resumen de tu solicitud:
*Producto solicitdado:* ${quote_accept.product}
*Presupuesto:* ${quote_accept.budget}
*Categoría:* ${quote_accept.category}
    
*Proveedor:* ${business.name}
*Precio Propuesto:* ${offer_accept.proposal_price}
*Mensaje del proveedor:* ${offer_accept.proposal_message}`)
await Whatsapp.sendMessage(PHONE_ID as string, customer_accept.phone, msg)
```

creating the text inside the sendMessage function doesn't work either, it was like that 
1. Simple and straight to the point failing snippet
2. See error
<img width="922" alt="Captura de pantalla 2023-10-01 a la(s) 7 32 33 p m" src="https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/aeeef220-3316-4f99-9e3e-d1d41dbec82f">

**Expected behavior**
create the Text Object to be able to send the message

Version: 2.1.2

Even   const txt = new Text('Hola', false); doesn' work 

<img width="757" alt="Captura de pantalla 2023-10-01 a la(s) 7 38 04 p m" src="https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/ecceafbb-9f3e-44a3-90e4-a5a4fcb03976">

**Comment by HysMX** [comment]
Had to rollback to 2.0.0 and it works now so something broke between 2.0.0 and 2.1.2

**Comment by Secreto31126** [comment]
Huh, that's weird. Let me check if I can replicate the issue.

**Comment by Secreto31126** [comment]
The only "big" change between 2.0.0 and 2.1.0 was the addition of `"sideEffects": false` to the package.json, which might have broken the messages/index.ts imports accidentally.

Would you mind trying out this beta release?

```sh
npm i whatsapp-api-js@2.0.1-beta.0
```

That release is exactly the same as v2 except for the side effects property. If it breaks too, it's definitely the reason.

**Comment by HysMX** [comment]
Working with 2.0.1-beta.0

**Comment by Secreto31126** [comment]
Wow, ok, that's absolutely unexpected.

Let's keep scaling. 2.1.0 contains almost no code change, most of the files are documentation and CI/CD. The only ts files changed were index.ts, template.ts and types.ts, so I expect it to work too.

```sh
npm i whatsapp-api-js@2.1.0
```

**Comment by Secreto31126** [comment]
Do you want to try out 2.1.3-beta.0? I removed the sideEffects property from package.json

**Comment by HysMX** [comment]
![image](https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/f83f6b9b-7c53-47b8-8829-53be2128c7fb)
2.1.3-beta.0 still says that

**Comment by Secreto31126** [comment]
I will close this as solved. The issue was a mismatching package and tsconfig.

For future reference, I recommend using the library with `"type": "module"` in package.json and `"target": "es6"`, `"module": "nodenext"` and `"skipLibCheck": true` in tsconfig.json, specially since CJS support might be dropped in the future.
