### ISSUE TITLE
Publish code without minifying

### ISSUE THREAD

**Issue by muniter** [Secreto31126/whatsapp-api-js#339]
**Is your feature request related to a problem? Please describe.**
I've had issues debugging the library:
1. Because it throws numbers (status codes) instead of errors, so there's no stack trace to look at or an error message.
2. Given the above I use the debugger, but when I get to the library code is minified as evident in [the build script](https://github.com/Secreto31126/whatsapp-api-js/blob/e6b52935995a22373fce95e629b7f099a26b999b/build.js#L14-15)

**Describe the solution you'd like**
1. Publish the code without minification, I believe this library only runs in the server, where the size savings by stripping whitespace and syntax are not important.

**Describe alternatives you've considered**
Trying to make vscode debugger load the source maps, but haven't been able, and think just publishing the unminified source to be a better approach.

**Additional context**
The change would be simple, just use default esbuild config:

```diff
diff --git a/build.js b/build.js
index 5b7569c..5bbe124 100644
--- a/build.js
+++ b/build.js
@@ -4,16 +4,11 @@ import { build } from "esbuild";
 import { glob } from "glob";
 import { writeFile } from "fs/promises";
 
-const production = process.env.NODE_ENV !== "development";
-
 /**
  * @type {import("esbuild").BuildOptions}
  */
 const sharedConfig = {
     entryPoints: await glob("src/**/*.ts", { ignore: ["src/standalone.ts"] }),
-    minifySyntax: production,
-    minifyWhitespace: production,
-    minifyIdentifiers: false,
     sourcemap: true,
     platform: "node"
 };
```

If agreed, I'm willing to send the pull request

**Comment by Secreto31126** [comment]
Hi! 

This has been at the back of my head for a few months. Back when I first started using esbuild, I had it misconfigured to bundle the output, which generated over 3 or 4mb builds. Although the library is mostly intended to be run on a server, I thought being so heavy would make the library untrustworthy, so I did my best to find a solution.

Now that the script is fixed, the package size is on the 600kb, which is still a little big for my liking, but it's way more reasonable that 2mb (it's 200kb for esm, 200kb for cjs and 200 for types + JSDoc + maps, so I doubt it can get any smaller).

If disabling the minification doesn't yield an output over 1mb, I will consider removing the flags.

I will run the tests on my notebook later today, thanks for the offer anyway!

**Comment by muniter** [comment]
Thank you! Let me know how it goes.

Size wise I think this package is great, searching for other similar packages I get:

- https://www.npmjs.com/package/@whiskeysockets/baileys: 76K downloads, 8.21MB
- https://www.npmjs.com/package/whatsapp-web.js: 16K downloads, 331KB
- https://www.npmjs.com/package/@wppconnect/wa-js: 2K downloads, 1.11MB

**Comment by Secreto31126** [comment]
I just did a beta release to check the new size, comparing with 3.0.1, the package size went from 652kb to 824kb. Bundlephobia, to no one's surprise, is down, but I'm gonna guess tree shaking is still enabled and everything is fine. 

It looks like it's a keeper. As soon as I get to charge my notebook I will do a proper release. 

Thanks for the help!

**Comment by muniter** [comment]
That sounds great. Thanks for following up!

**Comment by HysMX** [comment]
> Thank you! Let me know how it goes.
> 
> Size wise I think this package is great, searching for other similar packages I get:
> 
> * https://www.npmjs.com/package/@whiskeysockets/baileys: 76K downloads, 8.21MB
> * https://www.npmjs.com/package/whatsapp-web.js: 16K downloads, 331KB
> * https://www.npmjs.com/package/@wppconnect/wa-js: 2K downloads, 1.11MB

Those packages are emulators of the WhatsApp-web interface into a library form, so there's no comparison imo

**Comment by Secreto31126** [comment]
I'm so sorry I let this issue slide by, it has been a loooooong month at uni :)

I'm releasing 3.0.2 right now. Thanks for the patience!
