### ISSUE TITLE
_authenticatedRequest can be used only for GET requests.

### ISSUE THREAD

**Issue by yairiff** [Secreto31126/whatsapp-api-js#348]
There are features in the Cloud API that are not available through this package, so it is handy to have the ability to send authenticated requests to Meta without re-exposing the token (I specifically do message template registration).

The problem is that there is no way to define the method, only the url and other headers.
Just add the ability to control all the request options, rather than only headers.

**Comment by Secreto31126** [comment]
Hi! 

I find this topic to be a little controversial, as I don't like giving lead way for accidentally exposing the API key (such as fetching a malicious endpoint). However, it would also be nice to have the utility integrated in the class for more specific use cases.

I guess I can implement it for v4 and leave it well clarified in the documentation about the risks of the method. Maybe a more unusual name such as a $$ prefix might also help. 

Thanks for the idea!
