### ISSUE TITLE
How to use templates

### ISSUE THREAD

**Issue by wander4747** [Secreto31126/whatsapp-api-js#37]
Hi! I would like to know how to use a template-type message in this format.  And how do I change the text inside the pipes?
![image](https://user-images.githubusercontent.com/6461792/208531523-5c3a653a-0f49-4348-995e-605dd6a10cf9.png)

**Comment by Secreto31126** [comment]
To use the templates you will need:

- The name of the template
- The language of the template
- The Template class
- Any other class to fill the variables (pipes) and the buttons

The code should look somthing like this:

```js
// Ignoring all the setup configurations
const { Types } = require("whatsapp-api-js");
const { Template, BodyComponent, ButtonComponent, Text } = Types;

const message = new Template(
  "the_name_of_the_template",
  "br", // The language of the template, I'm assuming it will be Brazilian
  new BodyComponent(
    new Text("First variable goes here"),
    new Text("Second variable goes here")
    // There are more supported types for the body, such as DateTime
  ),
  new ButtonComponent(
    "quick_reply", // This is the type of the buttons, in your case is quick_reply
    "first_button_id",
    "second_button_id"
  )
);
```

The button's ids are used to handle the user's reply as follows:
```js
function onMessage(phoneID, phone, message, name) {
  if (message.type === "button") {
    const id = message.button.payload;
    // This id will be the same as the ones we defined before
  }
}
```

And that's it! Feel free to ask any other question.

[Template documentation](https://whatsappapijs.web.app/Template.html)

**Comment by wander4747** [comment]
Hi friend! Thank you  =)
