### ISSUE TITLE
interactive image header error

### ISSUE THREAD

**Issue by bassamtantawi-botpress** [Secreto31126/whatsapp-api-js#54]
I have a URL image added to the header, then sent with the interactive message. I received the below error:
```
{"error":{"message":"(#131009) Parameter value is not valid","type":"OAuthException","code":131009,"error_data":{"messaging_product":"whatsapp","details":"Text cannot be null for header type text"},"error_subcode":2494010,"fbtrace_id":"ADVfgNJuHt1I0vswkWjywNs"}}
{
  error: {
    message: '(#131009) Parameter value is not valid',
    type: 'OAuthException',
    code: 131009,
    error_data: {
      messaging_product: 'whatsapp',
      details: 'Text cannot be null for header type text'
    },
    error_subcode: 2494010,
    fbtrace_id: 'ADVfgNJuHt1I0vswkWjywNs'
  }
```

**Comment by Secreto31126** [comment]
Could you send me the output from the function:

```js
WhatsApp.logSentMessages((id, to, object) => console.log(object));
```

This will show the structure of the sent message to the API. However, keep in mind that the interactive header had been a little broken since #1, so I wouldn't be surprised if it's, once again, the same server side issue.

**Comment by bassamtantawi-botpress** [comment]
@Secreto31126 Here you go:
`{"type":"list","action":{"button":"this is a subtitle","sections":[{"title":"this is a title","rows":[{"id":"action_a","title":"Action A","description":" "}]}]},"body":{"text":"this is a title"},"header":{"type":"image","image":{"link":"[https://upload.wikimedia.org/wikipedia/commons/9/91/T-bone-raw-MCB.jpg"}},"footer":{"text":"this](https://upload.wikimedia.org/wikipedia/commons/9/91/T-bone-raw-MCB.jpg%22%7D%7D,%22footer%22:%7B%22text%22:%22this) is a title"}}`

**Comment by bassamtantawi-botpress** [comment]
It seems that footer is broken too (Without footer)
{"type":"list","action":{"button":"this is a subtitle","sections":[{"title":"this is a title","rows":[{"id":"action_a","title":"Action A","description":" "}]}]},"body":{"text":"this is a title"},"header":{"type":"image","image":{"link":"[https://upload.wikimedia.org/wikipedia/commons/9/91/T-bone-raw-MCB.jpg"}}}](https://upload.wikimedia.org/wikipedia/commons/9/91/T-bone-raw-MCB.jpg%22%7D%7D%7D)

**Comment by Secreto31126** [comment]
I think GitHub tried to parse the image's url with markdown 😆. Anyway, as I suspected, the framework is building the message as expected on the client, but the API freaks out because there's no text:

```json
{
    "type": "list",
    "action": {
        "button": "this is a subtitle",
        "sections": [
            {
                "title": "this is a title",
                "rows": [
                    {
                        "id": "action_a",
                        "title": "Action A",
                        "description": " "
                    }
                ]
            }
        ]
    },
    "body": {
        "text": "this is a title"
    },
    "header": {
        // This is the standard structure for images, which as stated in #1 it sometimes works and sometimes doesn't
        // At least with interactive buttons, never tested it with lists
        "type": "image",
        "image": {
            "link": "https://upload.wikimedia.org/wikipedia/commons/9/91/T-bone-raw-MCB.jpg"
        }
    }
}
```

**Comment by bassamtantawi-botpress** [comment]
I tried with buttons BTW

**Comment by Secreto31126** [comment]
On the other hand, [on the Postman documentation](https://www.postman.com/meta/workspace/whatsapp-business-platform/request/13382743-be4781ec-b59f-4aaa-8bf9-458ff4f29650), the example code for lists doesn't mention other types than texts. I will need to dive back into the documentation and see if there's any mention as how the API expects other headers types.

I will come back to this in an hour or so and test a bunch of things. Sorry for the inconvinience!

**Comment by bassamtantawi-botpress** [comment]
thanks @Secreto31126 in advance 🙂

**Comment by Secreto31126** [comment]
Ok, I think I did some progress. The [API documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#header-object) was updated and now includes a list of the valid headers types for each interactive.

Unfortunately, the only valid header for lists and multi products are texts (there's no mention of single products 🙄).

I will test with the other types and update the code to reject invalid headers for each type, preventing this error in the future.

Sorry for the bad news :/

**Comment by Secreto31126** [comment]
Well, I tested with all the interactive types and with images and videos, and unfortunately none works except for buttons. I will start writting the new checks for the header, and read a little more in search for other weird exceptions.

PS: The documentation didn't mention single products because they simply don't support headers, got my own code to tell me that 😄.

**Comment by bassamtantawi-botpress** [comment]
THank you very much for you efforts 🙂

**Comment by bassamtantawi-botpress** [comment]
@Secreto31126 what do you mean by "and unfortunately none works except for buttons"?

**Comment by Secreto31126** [comment]
None of the media types work as an interactive header except for buttons interactives. In other words, Media only works as a header for ActionButtons. I'm a pro at saying simple things the hard way :)

Anyway, a PR is on the oven, it should be ready in a few minutes.

**Comment by bassamtantawi-botpress** [comment]
Perfect, thank you @Secreto31126  :)
