### ISSUE TITLE
Road to 1.0.0

### ISSUE THREAD

**Issue by Secreto31126** [Secreto31126/whatsapp-api-js#62]
## Update

I'm unfortunately unable to fulfill the milestone set for today, and I will be unavailable for the next 2 weeks. I didn't get the time to set up a real bot to test the messages, specially since templates where the most affected and now they will be a paid feature.

On the other hand, I do believe that the code is ready to be shipped, so I could release V1 to NPM in a few minutes. I think I just need to do one more full re-read to feel confident.

Anyway, the changelog file will not be available, at least not in a month, and the docs will stay in this miserable state, unless I hack something together this night.

### Main goals:

- [x] Rewrite into TypeScript
- [x] Make the code more server agnostic
  - [x] Replace eventEmitter with something non Nodejs exclusive
  - [x] Make node:crypto module call optional, and fail on constructor if secure is `true` and module doesn't exists
- [x] Find out why Prettier is crying a lot lately 🙄
- [x] Find a way to keep previous versions of the documentation active, so they don't become unusable
- [x] Improve website docs by splitting each message into separate sections
- [x] Beta release to NPM
- [x] Write changelog and how to update from v0 to v1 (kinda done with #126)
- [x] Public release to NPM

### Aftermath:

- [x] Write step by step tutorials for setting up a bot (kinda done with EXAMPLES)

**Comment by mtariqsajid** [comment]
can you please also fix the issue with fetch, its crashing alot of time maybe use axios instead of fetch to make api calls

**Comment by Secreto31126** [comment]
The new version will allow users to pick their own request implementation or ponyfill, as long as it follows the same arguments as the standard fetch (which unfortunately axios doesn't follow, but node-fetch does). I think the code will be ready for friday, will do my best.

If you can't wait until the stable release, consider using the 1.0.0-beta.2 release on npm. It works afaik, and you can use the fetch method you want.

**Comment by mtariqsajid** [comment]
yeah the problem i am having its crash randomly, sometime it works but sometime it does not work. also it should throw exception instead of crashing the whole server.

**Comment by Secreto31126** [comment]
Sorry, I don't get it. Why is the server crashing? The code I wrote doesn't intentionally crash, it throws errors. Does using try/catch in your code prevents the crash?

If you want, lets move to a new issue and leave this one reserved for the roadmap.
