### ISSUE TITLE
should I not create a singleton version of this client ?

### ISSUE THREAD

**Issue by mtariqsajid** [Secreto31126/whatsapp-api-js#72]
**Describe the bug**
sometime this library crash the server. and i am not sure why its happening. I am currently use this in singleton pattern. If the object of this client exists i don't create another instance of this client.

**Desktop (please complete the following information):**
 - OS: linux
 - Node: 18

**Comment by Secreto31126** [comment]
May I get a snippet of the code that fails? I don't see why the singleton pattern wouldn't work (which is actually the prefered way), but there should be no issue in creating multiple instances of the class.

**Comment by mtariqsajid** [comment]
> May I see a snippet of the code that fails? I don't see why the singleton pattern wouldn't work (which is actually the prefered way), but there should be no issue in creating multiple instances of the class.

i am using adonis js 5 typescript
```
import { facebookConfig } from "Config/services";
import { WhatsAppAPI } from "whatsapp-api-js";

class Whatsapp {
  public WhatsappClient: WhatsAppAPI
  private booted = false

  public boot() {
    /**
     * Ignore multiple calls to the boot method
     */
    if (this.booted) {
      return
    }

    this.booted = true
    this.WhatsappClient = new WhatsAppAPI(facebookConfig.FB_WEBHOOK_ACCESS_TOKEN)
  }
}

export default new Whatsapp()
```

**Comment by mtariqsajid** [comment]
```
sendHelpTemplateTextMessage Error:
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8369:13)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
[20:16:05.387] FATAL (whatsapp-chatgpt/109499): "uncaughtException" detected
    TypeError: fetch failed
        at Object.fetch (node:internal/deps/undici/undici:11413:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20:16:05.388] WARN (whatsapp-chatgpt/109499): pino.final with prettyPrint does not support flushing
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[ warn ]  Underlying HTTP server died with "1 code"

```

sending message using this method
```
 await WhatsApp.WhatsappClient.sendMessage(phoneID, phone, new Text(message));
```

> Ok, from what I'm getting, the code generally works and the API is able to send messages. However, from time to time undici does a fatal crash and exits the whole script, right?
> 
> Could you send the code that fails? From your error stack I can't pin point what the issue is. Maybe it happens on a sendMessage call.
> 
> The singleton class doesn't seem to be an issue here.

**Comment by Secreto31126** [comment]
Well, unfortunately there's nothing I can do with this error. The stack log doesn't say anything to me, it seems to be an issue directly from fetch, and for some reason the stack doesn't mention any relation with whatsapp-api-js code.

Once again, I'm working on 1.0.0, which will remove the undici dependecy and allow any standard fetch to be used (such as node-fetch, which is known to be more stable). There are really few things left to publish one more beta release, and in a few days an official release. I will send you a message here when the beta is out so you can test it and check if it works or not.

Thanks for your patience

**Comment by Secreto31126** [comment]
Hi 👋, yesterday I released 1.0.0-beta.3 to npm, which includes the option to ponyfill the fetch implementation, hence removing undici fetch, which triggers this bug.

If you're interested in testing it, you can install it with:

```sh
npm i whatsapp-api-js@1.0.0-beta.3
```

In order to construct the framework with the ponyfill, you should call it like this:

```ts
import WhatsAppAPI from "whatsapp-api-js";

// As an example, you can use node-fetch
import fetch from "node-fetch";

const Whatsapp = new WhatsAppAPI({
    token: YOUR_SECRET_TOKEN,
    appSecret: YOUR_APP_SECRET,
    // If you don't want to set up the app secret, set secure to false
    // secure: false,
    ponyfill: {
        // Here you set the ponyfill you want to use
        fetch
    }
});
```

There are a few other breaking changes, like callbacks for on message and on status being defined within the class object instead of being called on the post handler.

Let me know if this works for you, and if your server stops halting for no apparent reason.

**Comment by Secreto31126** [comment]
I assume the new version is working as expected, I will close the issue as resolved.

Feel free to reopen if you come across it again.

**Comment by mtariqsajid** [comment]
I believe WhatsApp blocks or imposes rate limits on calls when users repeatedly send the same message to others within a short period of time. This is considered abusive behavior, which is why the library throws an error. This issue may affect others who are experiencing the same problem.

``` bash
cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8369:13)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }

```
