### ISSUE TITLE
Suggestion: whatsapp-api-ts

### ISSUE THREAD

**Issue by jbergstroem** [Secreto31126/whatsapp-api-js#89]
Hey,
came across this awesome project just now. Great job on the Typescript migration! Was just thinking that it would be appropriate to reserve the name `whatsapp-api-ts` on npm and optionally renaming this repo/project seeing how its now Typescript :-)

**Comment by Secreto31126** [comment]
I had been thinking about this lately, and although it makes sense, there are a few reasons I'm still not convinced.

First, I would hate loosing the stats the package got the last few weeks on npm. I know it's just a virtual number, but the higher the stats the more chances someone will find it and download it. (Plus, it fulfills my dopamine seeing higher numbers :)

Second, renaming the package would require renaming the documentation websites. With GitHub pages there should be no issue, but the one on Firebase (.web.app) would require a full recreation and also destroy the SEO. On the other hand, I had been thinking about moving to Vercel, but that also will take some time.

Last, and probably least, I think whatsapp-api-js is more catchy than whatsapp-api-ts. I'm not a native English speaker, so I'm not sure how well sounds in English, but I like it in Spanish. However, it's not a real reason not to change.

Ultimately, I think the rename would bring more problems than improvements, specially for still being a small package. However, I will not discard the idea yet, as it's still possible to apply other solutions, such as creating a placeholder package which redirects to the one with the original name.

I will add the issue to the road map and think about it for a few hours. Thanks for the issue 😁.

**Comment by jbergstroem** [comment]
Thanks for sharing your thoughts/arguments! Overall it doesn't really matter; just wanted to bring it up.

> Ultimately, I think the rename would bring more problems than improvements, specially for still being a small package.

_If_ you were to make a change, its often better to do it at the "small"/early stage.
